import { DB } from "./database.types"; // Database interface generated by prisma-kysely
import { createPool } from "mysql2";
import { Kysely, MysqlDialect } from "kysely";

const DB_URL = process.env.DB_URL;

if (!DB_URL) {
	console.error("Invalid DB_URL!");
	process.exit(1);
}

const dialect = new MysqlDialect({ pool: createPool(DB_URL) });

export const db = new Kysely<DB>({ dialect });
