import { DB } from "./database.types"; // Database interface generated by prisma-kysely
import { createPool } from "mysql2";
import { Kysely, MysqlDialect } from "kysely";

let connection: Kysely<DB> | null = null;

export function connectToDatabase(DB_URL: string | undefined) {
	if (!DB_URL) {
		console.error("Invalid DB_URL!");
		process.exit(1);
	}

	const dialect = new MysqlDialect({ pool: createPool(DB_URL) });

	connection = new Kysely<DB>({ dialect });
}

export function db() {
	if (!connection) {
		console.error("Disconnected from database!");
		process.exit(1);
	}

	return connection;
}
