import type { DB } from "./database.types"; // Database interface generated by prisma-kysely
import { createPool } from "mysql2";
import { Kysely, MysqlDialect } from "kysely";
import { logger } from "../logger";

let connection: Kysely<DB> | null = null;

export function connectToDatabase(DB_URL: string | undefined) {
	if (!DB_URL) {
		logger.fatal("Invalid DB_URL!");
		process.exit(1);
	}

	const dialect = new MysqlDialect({ pool: createPool(DB_URL) });

	connection = new Kysely<DB>({
		dialect,
		log: (e) => {
			if (e.level === "query") {
				logger.debug(`SQL: ${e.query.sql} - [${e.query.parameters.join(",")}]`);
			}
		},
	});
}

export function db() {
	if (!connection) {
		logger.fatal("Disconnected from database!");
		process.exit(1);
	}

	return connection;
}
